#!/bin/bash
sh -c "$(curl -sSfL https://release.solana.com/v1.18.2/install)"
sleep 2
source ~/.bashrc
echo 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bashrc
source .bashrc
sleep 10
