#!/bin/bash
sh -c "$(curl -sSfL https://release.solana.com/v1.18.2/install)"
sleep 2
# Добавляем Solana в PATH
export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

# Проверяем, есть ли уже такая строка в .bashrc
if ! grep -Fxq 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"' ~/.bashrc
then
    echo 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bashrc
    echo "Solana PATH добавлен в .bashrc"
else
    echo "Solana PATH уже есть в .bashrc"
fi
