# Model arguments
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Training arguments
max_steps: 100 # Original 450
num_train_epochs: 2
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-6
lr_scheduler_type: cosine
warmup_ratio: 0.1

# GRPO arguments
use_vllm: true
vllm_gpu_memory_utilization: 0.8
num_generations: 4
per_device_train_batch_size: 8
beta: 0.06
max_prompt_length: 64
max_completion_length: 128

# Logging arguments
logging_strategy: steps
logging_steps: 10
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 50
seed: 42

# Script arguments
public_maddr: "/ip4/38.101.215.12/tcp/30002"
host_maddr: "/ip4/0.0.0.0/tcp/38331"
max_rounds: 10000

# Model-specific arguments
model_name_or_path: Gensyn/Qwen2.5-1.5B-Instruct
output_dir: runs/gsm8k/multinode/Qwen2.5-1.5B-Instruct-Gensyn-Swarm
